version: "3"

services:
  mongo-sp:
    container_name: mongo-sp
    image: mongo:latest
    command: mongod --port 27018
    restart: always
    ports:
      - ${MONGODB_PORT:-27018}:${MONGODB_PORT:-27018}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    expose:
      - 27018

  sp_chatgpt_api:
    container_name: sp_chatgpt_api
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 app.app:app
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo-sp
    expose:
      - 8000

  mongo_express-sp:
    container_name: mongo-express-sp
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8082}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-sp
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27018}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=sp_chatgpt_api
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo-sp

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - sp_chatgpt_api
